default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: twitter-clone-teamone_development

test:
  <<: *default
  database: twitter-clone-teamone_test

production:
  <<: *default
  database: twitter-clone-teamone_production
  username: twitter-clone-teamone
  password: <%= ENV['TWITTER-CLONE-TEAMONE_DATABASE_PASSWORD'] %>
